client_secret: ''
user_agent: ''
client_id: ''
username: ''
password: ''
nsfw_subs:
  - gonewild
  - pussy
  - forcedbreeding
  - SluttyConfessions
  - dirtyr4r
  - dirtypenpals
  - OnlineAffairs
  - DirtySnapchat
  - dirtykikpals
  - kikpals
  - sextingfree
  - RandomActsOfBlowJob
  - BDSMpersonals
  - NSFWskype
  - RandomActsOfOralSex
  - eroticpenpals
removal_message: 'Hello /u/{}! Your submission was removed because you have participated in an NSFW subreddit'
